[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ripe-autotrain"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["textual"]

[project.scripts]
ripe_autotrain = "ripe_autotrain.dashboard:main"

[tool.setuptools.packages.find]
where = [".."]
include = ["ripe_autotrain*"]
